name: api tests with postman executed using newman cli
on:
  push:
    branch:
      - master
  pull_request:
    branch:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8'
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - run: npm install
      - run: npm install -g newman
      - name: Setup API and run tests
        run: |
          cd shell_scripts
          chmod +x ./wait-for-it.sh
          npm start &
          API_PID=$!
          ./wait-for-it.sh -t 60 localhost:5000 -- && sh ./run-all-api-tests.sh
          kill $API_PID
        env:
          DATABASE_URL: ${{secrets.PGCONN}}
          PORT: 5000
          NODE_ENV: development
